include("/Users/song/miniconda3/lib/python3.13/site-packages/cmake/data/share/cmake-4.4/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[lexer_tests]==]
  TEST_EXECUTABLE [==[/Users/song/Projects/VeriLens/build-cov/core/tests/lexer_tests]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[/Users/song/Projects/VeriLens/build-cov/core/tests]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[lexer_tests_TESTS]==]
  CTEST_FILE [==[/Users/song/Projects/VeriLens/build-cov/core/tests/lexer_tests_e3b0c442_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[/Users/song/Projects/VeriLens/build-cov/core/tests]==]
)
