if(EXISTS "/Users/song/Projects/VeriLens/build-cov/core/tests/parser_tests_e3b0c442_tests.cmake")
  include("/Users/song/Projects/VeriLens/build-cov/core/tests/parser_tests_e3b0c442_tests.cmake")
else()
  add_test(parser_tests_NOT_BUILT parser_tests_NOT_BUILT)
endif()
